### ISSUE TITLE
error after the installation

### ISSUE THREAD

**Issue by arademaker** [letuananh/intsem.fx#21]
```
% python -m coolisf text "I drink green tea." -f dmrs
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ar/venv/lib/python3.8/site-packages/coolisf/__main__.py", line 6, in <module>
    main.main()
  File "/Users/ar/venv/lib/python3.8/site-packages/coolisf/main.py", line 468, in main
    app.run()
  File "/Users/ar/venv/lib/python3.8/site-packages/texttaglib/chirptext/cli.py", line 135, in run
    args.func(self, args)
  File "/Users/ar/venv/lib/python3.8/site-packages/coolisf/main.py", line 230, in parse_text
    result = ghub.parse(text, args.grammar, args.topk, args.wsd, args.nocache, wsd=wsd, ctx=ctx)
  File "/Users/ar/venv/lib/python3.8/site-packages/coolisf/ghub.py", line 133, in parse
    sent = self[grm].parse(txt, parse_count=pc, ignore_cache=ignore_cache)
  File "/Users/ar/venv/lib/python3.8/site-packages/coolisf/ghub.py", line 226, in parse
    return self.parse_many((text,), parse_count, extra_args, ignore_cache)[0]
  File "/Users/ar/venv/lib/python3.8/site-packages/coolisf/ghub.py", line 221, in parse_many
    for sent in self.parse_many_iterative(texts, parse_count, extra_args, ignore_cache):
  File "/Users/ar/venv/lib/python3.8/site-packages/coolisf/ghub.py", line 179, in parse_many_iterative
    with ace.AceParser(self.gram_file, executable=self.ace_bin, cmdargs=args) as parser, self.cache.ctx() as ctx:
  File "/Users/ar/venv/lib/python3.8/site-packages/texttaglib/puchikarui/puchikarui.py", line 570, in ctx
    return self.ds.open(schema=self)
  File "/Users/ar/venv/lib/python3.8/site-packages/texttaglib/puchikarui/puchikarui.py", line 232, in open
    exe = ExecutionContext(self.path, schema=schema, auto_commit=ac)
  File "/Users/ar/venv/lib/python3.8/site-packages/texttaglib/puchikarui/puchikarui.py", line 376, in __init__
    self.conn = sqlite3.connect(str(path))
sqlite3.OperationalError: unable to open database file
```

I have to create the `local/isf/data/temp` manually. Maybe add that to https://coolisf.readthedocs.io/en/latest/?

**Comment by letuananh** [comment]
Thank you @arademaker. This seems to be a bug in the parse cache. I'll fix it and issue a patch asap.

**Comment by letuananh** [comment]
Fixed in: 140a9f5060cbbfbb2a7d2ec635825b93484dc0cb
To do:

- [ ] UAT
- [ ] Deploy patch to PyPI
